name: TSUM SOLD OUT

on:
  schedule:
    - cron: "*/5 * * * *"  # Каждые 5 минут
  workflow_dispatch:  # Можно запустить вручную

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3
      
      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Установка библиотек
        run: pip install requests beautifulsoup4 lxml
      
      - name: Запуск парсера
        run: python checker.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
      
      - name: Сохранение базы данных
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add products.json page_debug.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Обновление БД товаров"
          git push
